cd PWADS\brutalrec
start getwads.bat
cd ..\DEP
start getwads.bat
cd ..\light
start getwads.bat
cd ..\marcel
start getwads.bat
cd ..\SIGIL
start getwads.bat
cd ..\..\IWADS
start getwads.bat
cd ..\zandronum
start getzan.bat
start exzan.bat
cd ..\PWADS\brutalrec
start exwads.bat
cd ..\DEP
start exwads.bat
cd ..\light
start exwads.bat
cd ..\marcel
start exwads.bat
cd ..\SIGIL
start exwads.bat
cd ..\..\IWADS
start exwads.bat
