cd PWADS\brutalrec
call getwads.bat
cd ..\DEP
call getwads.bat
cd ..\light
call getwads.bat
cd ..\marcel
call getwads.bat
cd ..\SIGIL
call getwads.bat
cd ..\..\IWADS
call getwads.bat
cd ..\zandronum
call getzan.bat
call exzan.bat
cd ..\PWADS\brutalrec
call exwads.bat
cd ..\DEP
call exwads.bat
cd ..\light
call exwads.bat
cd ..\marcel
call exwads.bat
cd ..\SIGIL
call exwads.bat
cd ..\..\IWADS
call exwads.bat
